### PR TITLE
Scoped package

### PR DESCRIPTION
**Pull request by szkl**

### CODE REVIEW

**Comment by sinan** [comment]
this is already public do we need this to be scoped :)

**Comment by szkl** [comment]
Scoped packages can be public too. [koding/ndpane](https://github.com/koding/ndpane) will be present on npm registry as a separate package named `@koding/ndpane`. It'll be our version in the end.

**Comment by sinan** [comment]
fancy. :cocktail: :tropical_drink: :tropical_fish:

**Comment by szkl** [comment]
:dancers:

**Pull request merged**
